
services:
  - type: web
    name: user-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ./mvnw package
    startCommand: java -jar target/user-api-0.0.1-SNAPSHOT.jar
