name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilar y correr pruebas
        run: mvn clean verify

      - name: Subir reporte a Barecheck
        uses: barecheck/code-coverage-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          barecheck-token: ${{ secrets.BARECHECK_TOKEN }}
          coverage-files: "target/site/jacoco/jacoco.xml"
          base-branch-coverage-files: "target/site/jacoco/jacoco.xml"
          minimum-ratio: 70
